# ---------- Basics ----------
title: "Ze Rong"
name: "Ze Rong"
description: "AI for Medical Imaging & Sports Analytics"

url: "https://zerong7777-boop.github.io"   # 用户主页根域名
baseurl: ""                                # 用户主页必须留空
repository: "zerong7777-boop/zerong7777-boop.github.io"

# ---------- Theme (remote) ----------
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# 必须启用这个插件，否则 remote_theme 不会生效
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# ---------- Author sidebar ----------
author:
  name: "Ze Rong (荣泽)"
  avatar: "/images/profile.jpg"   # 放一张 400x400 的图到 /images/
  bio: "AI for Medical Imaging & Sports Analytics"
  email: "zerong7777 [at] gmail [dot] com"
  links:
    - label: "GitHub"
      url: "https://github.com/ZeRong7777"
    - label: "CV"
      url: "/files/CV_rz.pdf"

# ---------- Collections ----------
collections:
  publications: { output: true, permalink: /publication/:path/ }
  talks:        { output: true, permalink: /talks/:path/ }
  projects:     { output: true, permalink: /project/:path/ }

# ---------- Defaults ----------
defaults:
  - scope: { path: "", type: pages }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: posts }
    values: { layout: single, author_profile: true, read_time: true }
  - scope: { path: "", type: publications }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: talks }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: projects }
    values: { layout: single, author_profile: true }

# ---------- Misc ----------
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Asia/Taipei
