# ---------- Site basics ----------
title: "Ze Rong"
name: "Ze Rong"
description: "AI for Medical Imaging & Sports Analytics"

url: "https://zerong7777-boop.github.io"   # 用户主页根域名
baseurl: ""                                # 用户主页必须留空
repository: "zerong7777-boop/zerong7777-boop.github.io"

# ---------- 强制使用远程主题（含样式与布局） ----------
remote_theme: "mmistakes/minimal-mistakes@4.24.0"  # 直接拉 Minimal Mistakes
minimal_mistakes_skin: "default"

# ---------- Plugins (GitHub Pages 支持) ----------
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# ---------- Author (侧栏) ----------
author:
  name: "Ze Rong (荣泽)"
  avatar: "/images/profile.jpg"   # 放一张 400x400 到 /images/
  bio: "AI for Medical Imaging & Sports Analytics"
  email: "zerong7777 [at] gmail [dot] com"
  links:
    - label: "GitHub"
      url: "https://github.com/ZeRong7777"
    - label: "CV"
      url: "/files/CV_rz.pdf"

# ---------- Collections ----------
collections:
  publications:
    output: true
    permalink: /publication/:path/
  talks:
    output: true
    permalink: /talks/:path/
  projects:
    output: true
    permalink: /project/:path/

# ---------- Defaults（把 talk 的特殊布局改回 single，防止主题不兼容） ----------
defaults:
  - scope: {path: "", type: pages}
    values: {layout: single, author_profile: true}
  - scope: {path: "", type: posts}
    values: {layout: single, author_profile: true, read_time: true}
  - scope: {path: "", type: publications}
    values: {layout: single, author_profile: true}
  - scope: {path: "", type: talks}
    values: {layout: single, author_profile: true}
  - scope: {path: "", type: projects}
    values: {layout: single, author_profile: true}

# ---------- Misc ----------
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Asia/Taipei
